name = "textrender"
description = "Renders text using monospace fonts"
version = "1.0.0"
authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://github.com/bracke/textrender"
tags = ["textrender", "monospace"]
